-- 코드를 입력하세요
  
-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, TO_CHAR(B.CREATED_DATE, 'yyyy-mm-dd') as CREATED_DATE
    FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
    WHERE A.BOARD_ID = B.BOARD_ID AND TO_CHAR(A.CREATED_DATE, 'yyyymm') = '202210'
    ORDER BY B.CREATED_DATE, A.TITLE ASC;